config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  post 'users/login'
  get 'users/logout'
  get 'users/show_account'
  post 'users/add_balance'
  root 'users#index'

end

app/models/user_session.rb
class UserSession < Authlogic::Session::Base
end

app/models/user_transactions.rb
class UserTransactions < ActiveRecord::Base
end

app/models/users.rb
class Users < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user
  private
  	def current_user
		@current_user ||= Users.find(session[:user_id]) if session[:user_id]
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end
  def add_balance
    token=params[:stripeToken]
    amount=params[:amount].to_f
    charge = Stripe::Charge.create(
      :amount => (amount*100.00).to_i, # amount in cents
      :currency => "usd",
      :card => token,
      :description => "test"
    )
    if charge.paid
      UserTransactions.create(user_id:current_user.id ,amount:amount ,card_type:charge.card.brand,last4:charge.card.last4 ,transaction_id:charge.id)
      notice="successful"
    else
      notice="Failed"
    end
    respond_to do |format|
      format.json{render json:{paid:charge.paid,notice:notice}}
    end
    #binding.pry
  end
  def show_account
    @transactions=UserTransactions.where("user_id=?",current_user.id) if current_user
  end
  def login
  	user=Users.where("login=?",params[:login]).last
  	if user && params[:login]==params[:password]
  		session[:user_id]=user.id
  	end
  	redirect_to(:back)
  end
  def logout
  	session[:user_id]=nil
    redirect_to '/users/index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Stripe Demo</title>
    <%= stylesheet_link_tag   "sb-admin-2.css", "bootstrap.min.css","application", media: "all", "data-turbolinks-track" => true %>
    <link href="/assets/plugins/metisMenu/metisMenu.min.css" rel="stylesheet">
    <link href="/assets/plugins/dataTables.bootstrap.css" rel="stylesheet">
    <link href="/assets/css/font-awesome.min.css" rel="stylesheet" type="text/css">

    <%= javascript_include_tag "application","jquery-1.7.1.min.js",'stripe.js',"jquery.selection.js","sb-admin-2.js","bootstrap.min.js", "data-turbolinks-track" => true %> 
  	
    <script src="/assets/plugins/metisMenu/metisMenu.min.js"></script>
	<script src="/assets/plugins/dataTables/jquery.dataTables.js"></script>
    <script src="/assets/plugins/dataTables/dataTables.bootstrap.js"></script>
  	<%= csrf_meta_tags %>
</head>
<body>
	<div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
				<img class="img-responsive" src="/assets/logo.png" alt="">
            </div>
      

    <div class="navbar-default sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse"></div>
        </div>
    </nav>
    <br/>

    <div id="page-wrapper">
    	<h1 class="page-header">Stripe Demo</h1>
        <div class="col-lg-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                Steps to be followed for Stripe Demo.
            </div>
            <div class="panel-body">
                <p class="lead"></p>
                <p> 1) Enter Name and Password.</p>
                <p> 2) Click on the Submit button to LogIn.</p>
                <p> 3) Enter all the details mentioned ex: Name, Card Number, Expiry Date, Zip Code, CVV and Amount.</p>
                <p> 4) Fields marked with * are mandatory.</p>
                <p> 5) Click on the SUBMIT button and see the Account Balance sheet.</p>
                <p> 6) Click on the Sign Out and come out of the app.</p>
                <p> <h1>Test Card</h1></p>
                <p>    Name: Any Name </p>
                <p>    Card Number: 4242424242424242 </p>
                <p>    Expiry Date: Greater than today's Date </p>
                <p>    Zip Code: Any Valid Zip Code </p>
                <p>    CVV: 123 </p>
            </div>
        </div>
    </div>
    	<div class="col-lg-4">
            <div class="row">
                <div class="col-md-4 col-md-offset-4">
                    <div class="login-panel panel panel-default" style="margin-left: -70%; width: 240%;">
                        <div class="panel-heading">
                            <h3 class="panel-title">
                                <% if current_user %>
                                    Welcome <%= current_user.name %>!
                                    <%= link_to "Sign Out", users_logout_path,  :style=>"float:right" %>
                                <%else%>
                                    Please Sign In
                                <% end %>
                            </h3>
                        </div>
                        <div class="panel-body">
                            <%= yield %>   
                        </div>
                    </div>
                </div>
            </div>
        </div>   
    </div>
</body>
</html>

app/views/users/index.html.erb
<%if !current_user%>  
  <%=form_tag users_login_path do %>
    <fieldset>
      <div class="form-group">
        <label>Login</label>
        <%=text_field_tag "login",nil,:class=>'form-control',:placeholder=>'Enter Name' %>
      </div>
      <div class="form-group">
        <label>Password</label>
        <%=password_field_tag "password",nil,:class=>'form-control',:placeholder=>'Enter Password' %>
      </div>
      <%=submit_tag "Submit", :class=>'btn btn-lg btn-success btn-block' %>
    </fieldset>
  <%end%>
<%else%>
  <div id="paymentError" class="alert alert-danger" style="text-align:center;display:none"></div> 
  <%= form_tag '',:id=>"cardOnFileForm",:remote=>"true", :validate=>true,:class=>"register-form"  do %>
    <div class="form-group">
      <label>Name on Card</label>
      <%= text_field_tag "cardholder_name" ,nil,:placeholder =>"John Doe",:class=>"required form-control"%>
    </div>
    <div class="form-group">
      <label>* Card Number</label>
      <%= text_field_tag "card_number" ,nil,:placeholder =>"4444 4444 4444 4444",:class=>"required form-control"%>  
    </div>
    <div class="form-group">
      <label>* Expiry Date</label>
      <%= date_select 'expiration_date', nil,:discard_day => true, :start_year => Time.now.year-10, :end_year => Time.now.year+15,:order=>[:month,:year]%>
    </div>
    <div class="form-group">
      <label>Zip Code</label>
      <%= text_field_tag "zip_code" ,nil,:placeholder =>"22222",:class=>"required form-control"%>
    </div>
    <div class="form-group">
      <label>* CVV</label>
      <%= text_field_tag "card_cvv" ,nil,:placeholder =>"111",:class=>"required form-control"%>
    </div> 
    <div class="form-group">
      <label>* Amount</label>
      <%= text_field_tag "amount" ,nil,:placeholder =>"$",:class=>"required form-control"%>
    </div>        
    <div class="form-group">
      <label>&nbsp;</label>
      <span id="donationGif"><img src="/assets/stripe_loader.gif"></span>
    </div>      
    <div class="form-group">
      <label>&nbsp;</label>
      <%= submit_tag "SUBMIT", :class=>"btn btn-lg btn-success btn-block" ,:id=>"submit"%>
    </div>                         
    </br></br>
<% end %>                


<script type="text/javascript">
// Add your account publishable key in place of ################################
Stripe.setPublishableKey("#############################");
  
    $(document).ready( function()
    { 
      $("#donationGif").hide();
      function show_error(error)
      {
        $("#paymentError").show();
        $("#paymentError").fadeIn(1000).text(error);
        $("#submit").removeAttr("disabled").css({ cursor : "pointer" });      
      }  

    function stripeResponseHandler(status, response) {      
      if (response.error) {
        $("#donationGif").fadeOut(200);
        show_error(response.error.message);
      }else{
        $("#paymentError").fadeOut(1000);
        var form$ = $("#cardOnFileForm");
        var token = response['id'];
        form$.append("<input type='hidden' name='stripeToken' id='stripeToken' value='" + token + "'/>");
        $('#submit').attr("disabled", "disabled").css({ cursor : "default" });          
        
        $.ajax({ type: 'POST', url: "/users/add_balance", data: ({ 'stripeToken' : $("#stripeToken").val(),'amount' : $("#amount").val(),'user_id' :' <%=current_user.id%>','authenticity_token': "<%=form_authenticity_token%>"}), 
          success: function(data) {
            $("#donationGif").fadeOut(200);
            $("#submit").removeAttr("disabled").css({ cursor : "pointer" });
            if(data.paid){
              window.location.href='/users/show_account'
            }else{
              window.location.href='/users/index'
            }
          },
          error: function( ) {
            $("#submit").removeAttr("disabled").css({ cursor : "pointer" });
            $("#donationGif").fadeOut(200);
          }
        });                
      }
    }
    $('#cardOnFileForm').submit(function(event) { 
      $('#submit').attr("disabled", "disabled");
      $("#donationGif").fadeIn(200);
      Stripe.createToken({
        number: $('#card_number').val(),
        cvc: $('#card_cvv').val(),
        exp_month: $('#expiration_date__2i').val(),
        exp_year: $('#expiration_date__1i').val()
      }, stripeResponseHandler);
      return false;        
    });
  });

</script>
            
<%end%>

app/views/users/show_account.html.erb
<div class="table-responsive">
	<h1>Account Balance Sheet</h1>
    <table class="table table-striped table-bordered table-hover" id="dataTables-example">
	    <thead>
	        <tr>
	            <th>S No.</th>
	            <th>Date</th>
	            <th>Amount</th>
	            <th>Card Type</th>
	            <th>Card No</th>
	            <th>Transaction Id</th>
	        </tr>
	    </thead>
	    <tbody>
		    <%@transactions.each_with_index do |transaction,index|%>
		        <tr class="odd gradeX">
		            <td><%=index+1%></td>
					<td><%=transaction.created_at.to_date%></td>
					<td><%=number_to_currency(transaction.amount)%></td>
					<td><%=transaction.card_type%></td>
					<td>XXXX-XXXX-XXXX-<%=transaction.last4%></td>
					<td><%=transaction.transaction_id%></td>
				</tr>
			<%end%>   
	    </tbody>
	</table>
</div>